#!/usr/bin/env bash
# Tests for bin/fm-teardown.sh - thin wrapper that sources all split test files.
#
# The original fm-teardown.test.sh (3546 lines) was split into smaller files
# to reduce per-script test timeout under concurrent/loaded conditions.
# This wrapper sources the shared library and all split test files, then
# runs every test function in the same order the original file used.

# shellcheck source=tests/lib.sh
. "$(dirname "${BASH_SOURCE[0]}")/lib.sh"
# shellcheck source=tests/fm-teardown-lib.sh
. "$(dirname "${BASH_SOURCE[0]}")/fm-teardown-lib.sh"
set -u

fm_git_identity fmtest fmtest@example.invalid

# Source all split test files (each defines test_* functions only)
# shellcheck source=tests/fm-teardown-landed-work.sh
. "$(dirname "${BASH_SOURCE[0]}")/fm-teardown-landed-work.sh"
# shellcheck source=tests/fm-teardown-pr-check.sh
. "$(dirname "${BASH_SOURCE[0]}")/fm-teardown-pr-check.sh"
# shellcheck source=tests/fm-teardown-backlog-close.sh
. "$(dirname "${BASH_SOURCE[0]}")/fm-teardown-backlog-close.sh"
# shellcheck source=tests/fm-teardown-legacy-records.sh
. "$(dirname "${BASH_SOURCE[0]}")/fm-teardown-legacy-records.sh"
# shellcheck source=tests/fm-teardown-index-lock.sh
. "$(dirname "${BASH_SOURCE[0]}")/fm-teardown-index-lock.sh"
# shellcheck source=tests/fm-teardown-secondmate.sh
. "$(dirname "${BASH_SOURCE[0]}")/fm-teardown-secondmate.sh"
# shellcheck source=tests/fm-teardown-herdr.sh
. "$(dirname "${BASH_SOURCE[0]}")/fm-teardown-herdr.sh"
# shellcheck source=tests/fm-teardown-parked-run.sh
. "$(dirname "${BASH_SOURCE[0]}")/fm-teardown-parked-run.sh"
# shellcheck source=tests/fm-teardown-parked-run-edge.sh
. "$(dirname "${BASH_SOURCE[0]}")/fm-teardown-parked-run-edge.sh"
# shellcheck source=tests/fm-teardown-process-reap.sh
. "$(dirname "${BASH_SOURCE[0]}")/fm-teardown-process-reap.sh"

# Run all test functions in the original order
test_local_only_fork_remote_allows
test_teardown_closes_the_backlog_item_itself
test_teardown_manual_backend_leaves_the_backlog_to_the_operator
test_local_only_truly_unpushed_refuses
test_local_only_merged_to_local_main_allows
test_no_mistakes_origin_remote_allows
test_no_mistakes_truly_unpushed_refuses
test_local_only_force_overrides_unpushed
test_secondmate_pr_registration_publishes_ready_line
test_secondmate_home_teardown_delivers_final_line_or_refuses
test_teardown_missing_busy_sidecar_completes
test_herdr_teardown_clears_escalation_marker
test_herdr_flat_teardown_refuses_orphaning_records_then_retry_completes
test_herdr_flat_teardown_refuses_records_on_unparseable_presence
test_herdr_flat_teardown_preflight_refuses_before_changes
test_forced_secondmate_herdr_child_preflight_refuses_before_changes
test_forced_secondmate_teardown_holds_descendant_lifecycle_locks
test_forced_secondmate_herdr_child_retains_records_when_close_unconfirmed
test_forced_teardown_retains_nested_secondmate_home_when_grandchild_close_unconfirmed
test_herdr_projection_teardown_retires_journal_only_after_confirmed_close
test_herdr_projection_teardown_retains_journal_when_close_unconfirmed
test_herdr_projection_teardown_surfaces_restore_failure_without_blocking_cleanup
test_squash_merged_branch_deleted_allows
test_squash_merged_pr_allows_when_head_ancestor_of_pr_head
test_no_pr_recorded_discovers_merged_pr_by_branch_allows
test_squash_merged_pr_allows_replayed_unpushed_patch
test_merged_pr_with_later_local_commit_refuses
test_pr_check_does_not_refresh_stale_pr_head
test_pr_check_records_remote_head_when_local_lags
test_content_in_default_fallback_allows
test_content_fallback_refreshes_stale_origin_ref
test_dirty_worktree_refuses
test_gh_error_and_content_absent_refuses
test_legacy_record_without_the_flag_refuses
test_legacy_record_teardown_completes_when_landed_and_endpoint_dead
test_legacy_record_teardown_refuses_unlanded_work
test_legacy_record_teardown_refuses_an_ambiguous_endpoint
test_legacy_record_rolls_the_stamp_back_when_the_marker_write_fails
test_retained_legacy_stamp_still_faces_the_endpoint_gate
test_legacy_record_never_accepts_a_corrupt_spawn_gen
test_stale_index_lock_cleared_and_teardown_succeeds
test_live_index_lock_is_never_removed_and_teardown_refuses
test_lsof_error_never_clears_index_lock
test_stale_index_lock_cleanup_rechecks_dirty_worktree
test_non_linked_index_lock_path_is_checked_from_worktree
test_index_lock_mtime_read_failure_refuses
test_transient_index_lock_clears_after_first_attempt_and_retry_succeeds
test_persistent_index_lock_exhausts_retries_and_refuses_loudly
test_empty_retry_wait_uses_default_without_aborting
test_fractional_legacy_retry_wait_refuses_without_arithmetic_error
test_parked_own_run_is_aborted_before_teardown
test_parked_run_advanced_past_unfetched_head_is_still_aborted
test_parked_run_with_mismatched_ledger_head_is_never_aborted
test_parked_run_with_malformed_ledger_row_is_never_aborted
test_parked_run_with_impossible_ledger_date_is_never_aborted
test_terminal_status_with_gate_never_queries_or_aborts_ledger_fallback
test_parked_run_advanced_head_locally_fetched_is_still_aborted
test_parked_advanced_run_without_anchor_is_never_aborted
test_parked_advanced_run_ancestor_anchor_is_never_aborted
test_parked_terminal_unfetched_row_is_never_aborted
test_parked_run_terminal_newest_row_at_own_head_is_never_aborted
test_parked_run_behind_diverged_newer_row_is_never_aborted
test_parked_advanced_run_ambiguous_rows_are_never_aborted
test_ledger_proven_continuation_never_aborts_active_run
test_parked_own_run_refuses_when_abort_is_unconfirmed
test_mismatched_run_after_abort_refuses_unconfirmed
test_empty_status_after_abort_refuses_unconfirmed
test_not_found_status_after_abort_confirms_completion
test_another_branchs_parked_run_is_never_touched
test_own_autonomous_run_is_left_alone
test_leaked_worktree_process_is_reaped
test_leaked_tasktmp_process_is_reaped
test_lsof_absent_reaps_tmux_process_group
test_lsof_error_refuses_before_removal
test_reused_pid_identity_is_not_force_killed
test_exec_changed_process_is_still_reaped
test_process_spawned_during_grace_is_reaped_on_later_pass
test_persistent_scan_refuses_after_bounded_retries
test_process_exit_during_identity_lookup_does_not_refuse
test_run_abort_precedes_process_reap_precedes_worktree_removal
